### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by admiral96** [mozmeao/django-jinja-markdown#1]
I am unable to use with the 3 basic usages.
django1.9
python3.5.1

setup:

`settings.py`

    INSTALLED_APPS += (
        django_jinja,
        django_jinja_markdown,
    )
    TEMPLATES = [
        # Enabling markdown on templates
        {
            'BACKEND': 'django_jinja.backend.Jinja2',
            'OPTIONS': {
                'match_extension': '.jinja',
                'extensions': DEFAULT_EXTENSIONS + [
                    'django_jinja_markdown.extensions.MarkdownExtension',
                ],
            },
        },
        {
            # See: https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-TEMPLATES-BACKEND
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-dirs
            'DIRS': [
                str(APPS_DIR.path('templates')),
            ],
            'OPTIONS': {
                # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-debug
                'debug': DEBUG,
                # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-loaders
                # https://docs.djangoproject.com/en/dev/ref/templates/api/#loader-types
                'loaders': [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ],
                # See: https://docs.djangoproject.com/en/dev/ref/settings/#template-context-processors
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.template.context_processors.i18n',
                    'django.template.context_processors.media',
                    'django.template.context_processors.static',
                    'django.template.context_processors.tz',
                    'django.contrib.messages.context_processors.messages',
                    # Your stuff: custom template context processors go here
                ],
            },
        },
    ]

`index.html`

    {% extends "base.html" %}
    {% block content %}
      {% markdown %}
        {{ content }}
      {% endmarkdown %}
    {% endblock %}

`error traceback`

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
      File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python3.5/contextlib.py", line 30, in inner
        return func(*args, **kwds)
      File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
        return handler(request, *args, **kwargs)
      File "/app/es_dashboard/home/views.py", line 12, in get
        return render(request, 'pages/home.html', {'content': content})
      File "/usr/local/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
        template_name, context, request=request, using=using)
      File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 96, in render_to_string
        template = get_template(template_name, using=using)
      File "/usr/local/lib/python3.5/site-packages/django/template/loader.py", line 32, in get_template
        return engine.get_template(template_name, dirs)
      File "/usr/local/lib/python3.5/site-packages/django/template/backends/django.py", line 40, in get_template
        return Template(self.engine.get_template(template_name, dirs), self)
      File "/usr/local/lib/python3.5/site-packages/django/template/engine.py", line 190, in get_template
        template, origin = self.find_template(template_name, dirs)
      File "/usr/local/lib/python3.5/site-packages/django/template/engine.py", line 157, in find_template
        name, template_dirs=dirs, skip=skip,
      File "/usr/local/lib/python3.5/site-packages/django/template/loaders/cached.py", line 39, in get_template
        template_name, template_dirs, skip,
      File "/usr/local/lib/python3.5/site-packages/django/template/loaders/base.py", line 46, in get_template
        contents, origin, origin.template_name, self.engine,
      File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 189, in __init__
        self.nodelist = self.compile_nodelist()
      File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 231, in compile_nodelist
        return parser.parse()
      File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 516, in parse
        raise self.error(token, e)
      File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 514, in parse
        compiled_result = compile_func(self, token)
      File "/usr/local/lib/python3.5/site-packages/django/template/loader_tags.py", line 267, in do_extends
        nodelist = parser.parse()
      File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 510, in parse
        self.invalid_block_tag(token, command, parse_until)
      File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 572, in invalid_block_tag
        "or load this tag?" % (token.lineno, command)
    django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'markdown', expected 'endblock'. Did you forget to register or load this tag?

Please help me what am I doing wrong.

**Comment by robhudson** [comment]
Closing due to age.
